apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ['sh', '-c', 'echo "Hello, world!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here
